apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: demolab-argocd
  namespace: argocd
spec:
  applicationInstanceLabelKey: unixwarhammer.com/argoappname
  dex:
    openShiftOAuth: true
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      g, system:cluster-admins, role:admin
      g, argocd-users, role:readonly
      g, argocd-admins, role:admin
    scopes: '[groups]'
  repositories: |
    - url: https://github.com/ekrunch/argocd-test.git
  grafana:
    enabled: true
    route:
      enabled: true
  prometheus:
    enabled: true
    route:
      enabled: true
  server:
    route: 
      enabled: true
