apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: metering-ocp
  namespace: openshift-metering
spec:
  channel: "4.4"
  installPlanApproval: Automatic
  name: metering-ocp
  source: redhat-operators
  sourceNamespace: openshift-marketplace
