apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  namespace: nfs-provisioner
spec:
  selector:
    matchLabels:
      app: nfs-client-provisioner
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: nfs-client-prov
            - name: NFS_SERVER
              value: pepper.internal.unixwarhammer.com
            - name: NFS_PATH
              value: /volume2/ocpstorage
      volumes:
        - name: nfs-client-root
          nfs:
            server: pepper.internal.unixwarhammer.com
            path: /volume2/ocpstorage      
