apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
  labels:
    disk-type: hdd
    speed: slow
    volume-type: nfs4
provisioner: nfs-client-prov # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
